-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
FROM ICECREAM_INFO, FIRST_HALF
WHERE INGREDIENT_TYPE = 'fruit_based' AND TOTAL_ORDER > 3000 AND FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
ORDER BY TOTAL_ORDER DESC